package presentation;

import javax.swing.JPanel;

/**
 *
 * @author Alexander
 */
public class AuxiliarFrame extends javax.swing.JFrame {

    /**
     * Creates new form AuxiliarFrame
     */
    public AuxiliarFrame() {
        setTitle("Parcial Final Ing SW :D");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cambiarPanel(JPanel panel) {
        
        jScrollPane1.getViewport().setVisible(false);
        jScrollPane1.getViewport().removeAll();
        jScrollPane1.getViewport().add(panel);
        jScrollPane1.setSize(panel.getPreferredSize());
        jScrollPane1.getViewport().setVisible(true);
        this.setSize(this.getPreferredSize());
        this.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
