SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `MLG` ;
CREATE SCHEMA IF NOT EXISTS `MLG` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MLG` ;

-- -----------------------------------------------------
-- Table `MLG`.`MARKET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLG`.`MARKET` ;

CREATE  TABLE IF NOT EXISTS `MLG`.`MARKET` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(200) NOT NULL ,
  `NEMO` VARCHAR(200) NOT NULL ,
  `DESCRIPTION` VARCHAR(2000) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MLG`.`COMPANY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLG`.`COMPANY` ;

CREATE  TABLE IF NOT EXISTS `MLG`.`COMPANY` (
  `ID` INT NOT NULL ,
  `MARKET_ID` INT NOT NULL ,
  `NAME` VARCHAR(200) NOT NULL ,
  `SYMBOL` VARCHAR(200) NULL ,
  `DESCRIPTION` VARCHAR(2000) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_COMPANY_MARKET`
    FOREIGN KEY (`MARKET_ID` )
    REFERENCES `MLG`.`MARKET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_COMPANY_MARKET1` ON `MLG`.`COMPANY` (`MARKET_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MLG`.`STOCK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLG`.`STOCK` ;

CREATE  TABLE IF NOT EXISTS `MLG`.`STOCK` (
  `ID` INT NOT NULL ,
  `COMPANY_ID` INT NOT NULL ,
  `NAME` VARCHAR(200) NOT NULL ,
  `SYMBOL` VARCHAR(200) NOT NULL ,
  `DESCRIPTION` VARCHAR(2000) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_STOCK_COMPANY`
    FOREIGN KEY (`COMPANY_ID` )
    REFERENCES `MLG`.`COMPANY` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_STOCK_COMPANY1` ON `MLG`.`STOCK` (`COMPANY_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MLG`.`DATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLG`.`DATE` ;

CREATE  TABLE IF NOT EXISTS `MLG`.`DATE` (
  `ID` INT NOT NULL ,
  `DAY` INT NULL ,
  `MONTH` INT NULL ,
  `YEAR` INT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MLG`.`QUOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLG`.`QUOTE` ;

CREATE  TABLE IF NOT EXISTS `MLG`.`QUOTE` (
  `ID` INT NOT NULL ,
  `STOCK_ID` INT NOT NULL ,
  `DATE_ID` INT NOT NULL ,
  `LOW` DOUBLE NOT NULL ,
  `HIGH` DOUBLE NOT NULL ,
  `OPEN` DOUBLE NOT NULL ,
  `CLOSE` DOUBLE NOT NULL ,
  `VOLUME` DOUBLE NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_QUOTE_STOCK`
    FOREIGN KEY (`STOCK_ID` )
    REFERENCES `MLG`.`STOCK` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QUOTE_DATE`
    FOREIGN KEY (`DATE_ID` )
    REFERENCES `MLG`.`DATE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_QUOTE_STOCK1` ON `MLG`.`QUOTE` (`STOCK_ID` ASC) ;

CREATE INDEX `fk_QUOTE_DATE1` ON `MLG`.`QUOTE` (`DATE_ID` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
